TAGS='
label;aligny
fadelabel;label;done
fadelabel;info;done
fadelabel;font
fadelabel;textcolor
fadelabel;textoffsetx;done
fadelabel;shadowcolor;done
fadelabel;angle;done
fadelabel;scrollout;done;check
fadelabel;pauseatend;done;check
fadelabel;resetonlabelchange;done
fadelabel;scrollspeed;done
fadelabel;description;done
fadelabel;type;done
fadelabel;id;done
fadelabel;posx
fadelabel;posy
fadelabel;width;done;<width>400</width>
fadelabel;height;done;<height>25</height>
fadelabel;visible;done
fadelabel;animation;done
fadelabel;camera;done
fadelabel;colordiffuse;done
image;aspectratio;done
image;texture
image;bordertexture;done
image;bordersize;done
image;info;done
image;fadetime;done
image;description;done
image;type;done
image;id;done
image;posx
image;posy
image;width;done;<width>150</width>
image;height;done;<height>40</height>
image;visible;done
image;animation;done
image;camera;done
image;colordiffuse;done
label;align;done;<align>left</align>
label;aligny;done;<aligny>center</aligny>
label;scroll;done;<scroll>false</scroll>
label;label
label;info;done
label;number;done
label;angle;done
label;haspath;done
label;font
label;textcolor
label;shadowcolor;done
label;wrapmultiline;done
label;scrollspeed;done
label;scrollsuffix;done
label;description;done
label;type;done
label;id;done
label;posx
label;posy
label;width;done;<width>200</width>
label;height;done;<height>40</height>
label;visible;done
label;animation;done
label;camera;done
label;colordiffuse;done
button;texturefocus
button;texturenofocus
button;label;done
button;font
button;textcolor
button;focusedcolor;done
button;disabledcolor
button;shadowcolor;done
button;angle;done
button;align;done
button;aligny
button;textoffsetx
button;textoffsety;done
button;textwidth;done
button;onclick;done
button;onfocus;done
button;onunfocus;done
button;description;done
button;type;done
button;id;done
button;posx
button;posy
button;width
button;height
button;visible;done
button;animation;done
button;camera;done
button;colordiffuse;done
togglebutton;texturefocus
togglebutton;texturenofocus
togglebutton;alttexturefocus
togglebutton;alttexturenofocus
togglebutton;usealttexture;done
togglebutton;label
togglebutton;altlabel;done
togglebutton;font
togglebutton;textcolor
togglebutton;disabledcolor
togglebutton;shadowcolor;done
togglebutton;align;done
togglebutton;aligny;done
togglebutton;textoffsetx;done
togglebutton;textoffsety;done
togglebutton;onclick;done
togglebutton;onfocus;done
togglebutton;onunfocus;done
togglebutton;description;done
togglebutton;type;done
togglebutton;id;done
togglebutton;posx
togglebutton;posy
togglebutton;width
togglebutton;height
togglebutton;visible;done
togglebutton;animation;done
togglebutton;camera;done
togglebutton;colordiffuse;done
textbox;font
textbox;textcolor
textbox;shadowcolor;done
textbox;pagecontrol;done
textbox;autoscroll;done
textbox;description;done
textbox;type;done
textbox;id;done
textbox;posx
textbox;posy
textbox;width
textbox;height
textbox;visible;done
textbox;animation;done
textbox;camera;done
textbox;colordiffuse;done
progress;reveal;done
progress;texturebg
progress;lefttexture
progress;midtexture
progress;righttexture
progress;overlaytexture
progress;info;done
progress;description;done
progress;type;done
progress;id;done
progress;posx
progress;posy
progress;width;done;<width>280</width>
progress;height;done;<height>16</height>
progress;visible;done
progress;animation;done
progress;camera;done
progress;colordiffuse;done
spincontrol;textureup;done
spincontrol;textureupfocus
spincontrol;texturedown
spincontrol;texturedownfocus
spincontrol;font
spincontrol;textcolor
spincontrol;disabledcolor
spincontrol;shadowcolor;done
spincontrol;subtype
spincontrol;align
spincontrol;aligny
spincontrol;textoffsetx
spincontrol;textoffsety
spincontrol;type;done
spincontrol;id;done
spincontrol;posx
spincontrol;posy
spincontrol;width
spincontrol;height
spincontrol;visible;done
spincontrol;animation;done
spincontrol;camera;done
spincontrol;colordiffuse;done
spincontrolex;texturefocus
spincontrolex;textureup
spincontrolex;textureupfocus
spincontrolex;texturedown
spincontrolex;texturedownfocus
spincontrolex;label;done
spincontrolex;font
spincontrolex;textcolor
spincontrolex;disabledcolor
spincontrolex;shadowcolor;done
spincontrolex;align;done
spincontrolex;aligny
spincontrolex;textoffsetx
spincontrolex;textoffsety;done
spincontrolex;type;done
spincontrolex;id;done
spincontrolex;posx
spincontrolex;posy
spincontrolex;width
spincontrolex;height
spincontrolex;visible;done
spincontrolex;animation;done
spincontrolex;camera;done
spincontrolex;colordiffuse;done
radiobutton;texturefocus
radiobutton;textureradioon;done
radiobutton;textureradiooff;done
radiobutton;label
radiobutton;font
radiobutton;textcolor
radiobutton;focusedcolor;done;<focusedcolor>white</focusedcolor>
radiobutton;disabledcolor
radiobutton;shadowcolor;done
radiobutton;align;done;<align>left</align>
radiobutton;aligny
radiobutton;textoffsetx
radiobutton;textoffsety;done
radiobutton;selected;done
radiobutton;onclick;done
radiobutton;radioposx;done
radiobutton;radioposy;done
radiobutton;radiowidth
radiobutton;radioheight
radiobutton;onfocus;done
radiobutton;onunfocus;done
radiobutton;type;done
radiobutton;id;done
radiobutton;posx
radiobutton;posy
radiobutton;width
radiobutton;height
radiobutton;visible;done
radiobutton;animation;done
radiobutton;camera;done
radiobutton;colordiffuse;done
selectbutton;texturefocus
selectbutton;texturebg
selectbutton;textureleft
selectbutton;textureleftfocus
selectbutton;textureright
selectbutton;texturerightfocus
selectbutton;label
selectbutton;font
selectbutton;textcolor
selectbutton;disabledcolor
selectbutton;shadowcolor;done
selectbutton;align;done
selectbutton;aligny
selectbutton;textoffsetx;done
selectbutton;textoffsety;done
selectbutton;type;done
selectbutton;id;done
selectbutton;posx
selectbutton;posy
selectbutton;width
selectbutton;height
selectbutton;visible;done
selectbutton;animation;done
selectbutton;camera;done
selectbutton;colordiffuse;done
slider;texturesliderbar;done;<texturesliderbar>-</texturesliderbar>
slider;textureslidernib;done;<textureslidernib>controls/slider/nib-nf_light.png</textureslidernib>
slider;textureslidernibfocus;done;<textureslidernibfocus>controls/slider/nib-fo_light.png</textureslidernibfocus>
slider;controloffsetx
slider;controloffsety
slider;info;done
slider;action;done
slider;type;done
slider;id;done
slider;posx;done
slider;posy;done
slider;width;done;<width>720</width>
slider;height;done;<height>16</height>
slider;visible;done
slider;animation;done
slider;camera;done
slider;colordiffuse;done
sliderex;textoffsetx
sliderex;aligny
sliderex;texturefocus
sliderex;texturenofocus
sliderex;sliderwidth
sliderex;sliderheight
sliderex;texturesliderbar
sliderex;textureslidernib
sliderex;textureslidernibfocus
sliderex;font
sliderex;focusedcolor;done;<focusedcolor>white</focusedcolor>
sliderex;textcolor
sliderex;disabledcolor
sliderex;pulseonselect
sliderex;type;done
sliderex;id;done
sliderex;posx;done
sliderex;posy;done
sliderex;width;done
sliderex;height
sliderex;visible;done
sliderex;animation;done
sliderex;camera;done
sliderex;colordiffuse;done
mover;texturefocus
mover;texturenofocus
mover;type;done
mover;id;done
mover;posx
mover;posy
mover;width;done;<width>128</width>
mover;height;done;<height>128</height>
mover;visible;done
mover;animation;done
mover;camera;done
mover;colordiffuse;done
resize;texturefocus
resize;texturenofocus
resize;type;done
resize;id;done
resize;posx
resize;posy
resize;width;done
resize;height;done
resize;visible;done
resize;animation;done
resize;camera;done
resize;colordiffuse;done
edit;aligny
edit;label;done
edit;hinttext;done
edit;font
edit;textcolor
edit;type;done
edit;id;done
edit;posx
edit;posy
edit;width
edit;height
edit;visible;done
edit;animation;done
edit;camera;done
edit;colordiffuse;done
multiimage;imagepath
multiimage;info
multiimage;timeperimage
multiimage;fadetime
multiimage;pauseatend
multiimage;loop
multiimage;aspectratio
multiimage;type
multiimage;id
multiimage;posx
multiimage;posy
multiimage;width
multiimage;height
multiimage;visible
multiimage;animation
multiimage;camera
multiimage;colordiffuse
panel;width
scrollbar;width
'

DEF='
spincontrol;type
spincontrol;id
spincontrol;posx
spincontrol;posy
spincontrol;width
spincontrol;height
spincontrol;visible
spincontrol;animation
spincontrol;camera
spincontrol;colordiffuse
'

IFS=$'\n' ; for T in $TAGS ; do
	if $(echo "$T" | cut -f3 -d';' | grep -q 'done' ) ; then
		continue
	fi
	CONTROL=$(echo "$T" | cut -f1 -d';')
	TAG=$(echo "$T" | cut -f2 -d';')
	DEFSTART=$(grep -n '<default type="'"$CONTROL"'">' 720p/defaults.xml | cut -f1 -d:)
	if [ ! -z "$DEFSTART" ] ; then
		DEFSTOP=$(tail -n+"$DEFSTART" 720p/defaults.xml | grep -n '</default>' | head -n 1 | cut -f1 -d:)
		DEFTAG=$(tail -n+"$DEFSTART" 720p/defaults.xml | head -n "$DEFSTOP" | grep -v '<[/]*default' | \
			grep "<$TAG[ >]" | sed 's|^\s*||' )
	else
		DEFTAG=""
	fi
	
	#if ! [ -z "$DEFTAG" ] ; then
	#	continue
	#fi
	printf "\nControl is '$CONTROL', tag is '$TAG'."
	#printf "\nThere is no default tag."
	
	2>/dev/null rm tags.tmp
	EMPTY=0
	COUNT=0
	INCS=0
	for F in 720p/* ; do
		IFS=$'\n' ; for CONTROLSTART in $(grep -n '<control type="'"$CONTROL"'"' "$F" | cut -f1 -d:)
		do
			let COUNT=COUNT+1
			CONTROLSTOP=$(tail -n+"$CONTROLSTART" "$F" | grep -n '</control>' | head -n 1 | cut -f1 -d:)
			STRUCT=$(tail -n+"$CONTROLSTART" "$F" | head -n "$CONTROLSTOP" )
			STAG=$(echo "$STRUCT" | grep "<$TAG[ >]" | sed 's|^\s*||' )
			if echo "$STRUCT" | grep "<include>" ; then
				let INCS=INCS+1
			else
				if [ -z "$STAG" ] ; then
					let EMPTY=EMPTY+1
				else
					echo "$STAG" >>tags.tmp
				fi
			fi
		done
	done
	printf "\n$COUNT '$CONTROL' controls."
	#printf "\n%d controls with <include> tags." $INCS
	printf "\n%d controls with missing tags.\n" $EMPTY
	#printf "\nMost frequent tag:\n"
	2>/dev/null more tags.tmp | sort --batch-size=1021 | uniq -c | sed 's|^\s*||' | sort -r -n | head -n 5
done