TEXLIST='
arrow-big-[a-z]*.png;0
BackgroundEffect/rain-drop.png;0
banner/[a-zA-Z]*.png;0
banner/\$LOCALIZE\[16102\].png;0
black-back2.png;0
black-back.png;0
buttons/fo_light.png;0
buttons/nf_light.png;0
Calibrate[a-zA-Z]*.png;0
cdwall-grid.png;0
DefaultFile.png;0
DefaultIconError.png;0
DefaultIconInfo;0
DefaultIconWarning;0
epg-genres/\$INFO\[ListItem.Property\(GenreType\)\].png;3
FallbackAlbumCover.png;0
Fanart_Fallback_Music_Small.jpg;0
Fanart_Fallback_Small.jpg;0
flagging/blank.png;4
flagging/video/3D.png;0
floor_buttonFO.png;5
floor_button.png;5
folder-focus_light.png;6
GoFullscreen.png;0
HomeBack.png;0,6,0,6
HomeBladeSub_light.png;7,0,7,0
HomeNowPlayingBack.png;0
HomeSubEnd.png;0,2,0,2
HomeSubFO.png;2
HomeSubNF_light.png;0,2,0,0
icon_[a-z]*.png;0
icon-[a-z]*.png;0
\$INFO\[[A-Za-z0-9\.,/\(\)_]*\];0
KeyboardEditArea_light.png;0
lastfm/[a-z-]*.png;0
LeftRating/\$INFO\[ListItem.StarRating\];0
MediaBladeSub_light.png;7,0,7,0
NoCover_1.png;4
OSD[a-zA-Z0-9]*.png;0
progressbar/OSDProgressBack_light.png;0
progressbar/OSDProgressMidLight_light.png;0
progressbar/OSDProgressMid_light.png;0
osd_slider_bg_2.png;0
osd_slider_nibNF.png;0
osd_slider_nib.png;0
OverlayStatus/resumable/OverlayUnwatched.png;0
OverlayWatched.png;0
pointer-[a-z-]*.png;0
PVR-[A-Za-z]*.png;0
radiobutton-nofocus.png;0
scroll-down-2.png;0
scroll-down-focus-2.png;0
scroll-down-focus.png;0
scroll-down.png;0
scroll-left-focus.png;0
scroll-left.png;0
scroll-right-focus.png;0
scroll-right.png;0
scroll-up-2.png;0
scroll-up-focus-2.png;0
scroll-up-focus.png;0
scroll-up.png;0
seekslider_light.png;0
special://skin/backgrounds/default_light.jpg;0
special://skin/backgrounds/settings.jpg;0
StackFO.png;3
StackNF.png;3
unknown-user.png;0
\$VAR\[[a-zA-Z,\.\/]*\];0
VolumeIcon.png;0
warning.png;0
'