TEXLIST='
BackgroundEffect/rain-drop.png;0
banner/[^\.]*.png;0
buttons/folder-focus_light.png;7
buttons/[nfo]*_light.png;0
buttons/spin-[a-z-]*.png;0
buttons/calibrate/[a-z_]*.png;0
Default[a-zA-Z]*.png;0
dialogs/bladesub_light.png;4,0,4,0
dialogs/overlay-background.png;0
epg-genres/[0-9]*.png;3
Fanart_Fallback_Music_Small.jpg;0
Fanart_Fallback_Small.jpg;0
flagging/blank.png;4
flagging/video/3D.png;0
floor_buttonFO.png;5
floor_button.png;5
GoFullscreen.png;0
HomeBack.png;0,6,0,6
HomeNowPlayingBack.png;0
HomeSubEnd.png;0,2,0,2
home/sub-[nfo]*_light.png;0,2,0,2
icon_[a-z]*.png;0
icon-[a-z]*.png;0
\$INFO\[[A-Za-z0-9\.,/\(\)_]*\];0
KeyboardEditArea_light.png;0
lastfm/[a-z-]*.png;0
LeftRating/\$INFO\[ListItem.StarRating\];0
NoCover_1.png;4
OSD[a-zA-Z0-9]*.png;0
osd_slider_bg_2.png;0
osd_slider_nibNF.png;0
osd_slider_nib.png;0
OverlayStatus/resumable/OverlayUnwatched.png;0
OverlayWatched.png;0
pointer-[a-z-]*.png;0
progressbar/OSDProgressBack_light.png;0
progressbar/OSDProgressMidLight_light.png;0
progressbar/OSDProgressMid_light.png;0
PVR-[A-Za-z]*.png;0
radiobutton-focus.png;0
radiobutton-nofocus.png;0
scroll-left-focus.png;0
scroll-left.png;0
scroll-right-focus.png;0
scroll-right.png;0
seekslider_light.png;0
special://skin/backgrounds/default_light.jpg;0
special://skin/backgrounds/settings.jpg;0
StackFO.png;3
StackNF.png;3
unknown-user.png;0
\$VAR\[[a-zA-Z,\.\/]*\];0
VolumeIcon.png;0
warning.png;0
'